import { Meal } from './meal';

export const MEALS: Meal[] = [
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    {name: 'tempname', calories: 69, ingredients: 'tempingredients', instructions: 'tempinstructions'},
    
]